# Generated by Django 4.1 on 2022-10-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionServicios', '0003_agendamiento_condicion_entidad_salud_oficio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad_salud',
            name='direccion',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='entidad_salud',
            name='telefono',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='entidad_salud',
            name='valor_es',
            field=models.IntegerField(),
        ),
    ]
