# Generated by Django 4.1 on 2022-10-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionServicios', '0004_alter_entidad_salud_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad_salud',
            name='ciudad',
            field=models.CharField(max_length=45, verbose_name='Ciudad Sede Principal'),
        ),
    ]
