# Generated by Django 4.1 on 2022-10-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionServicios', '0005_alter_entidad_salud_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellidos_u',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='documento_u',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombres_u',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
