# Generated by Django 4.1 on 2022-10-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionServicios', '0006_alter_usuarios_apellidos_u_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha_t',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellidos_u',
            field=models.CharField(max_length=45, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='documento_u',
            field=models.CharField(max_length=45, null=True, unique=True, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombres_u',
            field=models.CharField(max_length=45, null=True, verbose_name='Nombres'),
        ),
    ]
