# Generated by Django 4.1 on 2022-10-15 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionServicios', '0007_alter_transaccion_fecha_t_alter_usuarios_apellidos_u_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicios',
            name='nombre_idServicios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionServicios.servicios'),
            preserve_default=False,
        ),
    ]
